**Importing the datasets**


In [1]:
from sklearn.datasets import load_iris

KFold import

In [2]:
from sklearn.model_selection import cross_val_score

Import ML models


In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [5]:
iris = load_iris()

In [20]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset('iris')


In [21]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [27]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
l_scores = cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [31]:
import numpy as np
np.average(l_scores)

np.float64(0.9733333333333334)

In [32]:
d_scores = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [33]:
np.average(d_scores)

np.float64(0.9600000000000002)

In [34]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [35]:
np.average(s_scores)

np.float64(0.9666666666666666)

In [40]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=55), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [41]:
np.average(r_scores)

np.float64(0.9666666666666668)

In [46]:
print("Score of LogisticRegression =",np.average(l_scores))
print("Score of DecisionTreeClassifier =",np.average(d_scores))
print("Score of SupportVectorMachine =",np.average(s_scores))
print("Score of RandomForestClassifier =",np.average(r_scores))

Score of LogisticRegression = 0.9733333333333334
Score of DecisionTreeClassifier = 0.9600000000000002
Score of SupportVectorMachine = 0.9666666666666666
Score of RandomForestClassifier = 0.9666666666666668


**So Logistic Regression has best score**